FROM ubuntu:20.04
RUN apt update
RUN apt upgrade -y
RUN apt install telnet -y
RUN apt install vim -y
RUN apt install curl -y
RUN apt install iputils-ping -y
RUN apt install mysql-client -y 
CMD ["sleep", "3600"]